### ISSUE TITLE
feature Request - Unable to capture file binaries  - latest release 2.0.1.2

### ISSUE THREAD

**Issue by mboxraj** [RickStrahl/WestWindWebSurge#91] opened 2022-02-11 06:42 UTC
We are not able to capture attachment files during recording session using latest build 2.0.1.2

Thanks
Rajesh

**Comment by RickStrahl** [comment] 2022-02-11 21:52
Unfortunately this appears to be a bug in the WebView control that we are using to capture the request data while browsing in the previewer. It looks like the WebView is not returning the multipart/form request content stream when navigating to new resources.

Issue is tracked here on the WebView2 Repository:

[CoreWebView2_WebResourceRequested not providing binary multi-part POST Data in Request.Content #2162
](https://github.com/MicrosoftEdge/WebView2Feedback/issues/2162)

**Comment by mboxraj** [comment] 2022-03-29 12:45
@RickStrahl   tried reaching you from my work account to rstrahl@west-wind.com but couldn't get any reply so trying from here. We have licensed version now but still seeing file upload issues, can you pls help us.

**Comment by RickStrahl** [comment] 2022-04-09 01:31
To close this out for now - for any requests that require binary file uploads you will have to create the request form data manually as the WebView currently does not capture that data. 

[The form editor allows you to manually add the binary and text multi-part form variables](https://websurge.west-wind.com/docs/_69z0ym9oi.htm#the-interactive-form-editor) to each request which is the only workaround available for the moment.

Still leaving this open in hopes that updated WebView releases get this fixed. The issue is tagged and known by the WebView team but no word on whether it will get fixed.

**Closed** 2022-04-20 01:12 UTC
Labels: bug, waiting for upstream fix
