### ISSUE TITLE
Add New User - Add Form Variable

### ISSUE THREAD

**Issue by inthegarden** [RickStrahl/WestWindWebSurge#97] opened 2022-05-09 16:04 UTC
09/05/2022 17:03:30 - Critical - AppDispatcher: Object reference not set to an instance of an object.
Object reference not set to an instance of an object.
WebSurge v2.1.4.0
10.0.19041.1.amd64fre.vb_release.191206-1406 - en-GB - NET 4.8 - 64 bit
en-GB - en-GB    
---
WebSurge
   at WebSurge.Windows.UserContentControl.ButtonAddNewUrl_Click(Object sender, RoutedEventArgs e) in C:\projects\WebSurge2\WebSurge\Windows\Users\UserContentControl.xaml.cs:line 84
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
System.NullReferenceException

**Comment by RickStrahl** [comment] 2022-05-10 01:50
Hmmm... looks like a regression bug that's causing users to not get added correctly and the form actually not having a user active. 

Updated and fixed for the next update. 2.1.3.2+

**Comment by inthegarden** [comment] 2022-05-10 04:48
Thanks for the quick response Rick! When might the next update be out? Thx

**Comment by RickStrahl** [comment] 2022-09-07 05:38
Should have been fixed with release 2.1.5 a while ago.

**Closed by RickStrahl** 2022-09-07 05:38 UTC
